/* eslint-disable import/prefer-default-export */
export const DEFAULT_PREVIEW_TEXT = ''

export enum IpcAction {
  SYNC_DATA = 'SYNC_DATA',
  SAVE_AND_EXIT = 'SAVE_AND_EXIT',
  OPEN_NODE_IN_MEX = 'OPEN_NODE_IN_MEX',
  OPEN_NODE = 'OPEN_NODE',
  GET_LOCAL_DATA = 'GET_LOCAL_DATA',
  SET_LOCAL_DATA = 'SET_LOCAL_DATA',
  SAVE_AND_QUIT = 'SAVE_AND_QUIT',
  SELECTED_TEXT = 'SELECTED_TEXT',
  SPOTLIGHT_BUBBLE = 'SPOTLIGHT_BUBBLE',
  NEW_RECENT_ITEM = 'NEW_RECENT_ITEM',
  SPOTLIGHT_BLURRED = 'SPOTLIGHT_BLURRED',
  CLEAR_RECENTS = 'CLEAR_RECENTS',
  RECIEVE_LOCAL_DATA = 'RECIEVE_LOCAL_DATA',
}
