name: Build and Release on macOS
on:
  push:
    branches:
      - "mukul-wd-1020-task-auto-deploy-mex-releases"

jobs:
  create_github_release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  publish_on_mac_x64:
    runs-on: macos-latest
    needs: create_github_release
    env:
      GITHUB_TOKEN: ${{ github.token }}
      YARN_TOKEN: ${{ secrets.YARN_TOKEN }}
      CERTIFICATE_OSX_P12: ${{ secrets.CERTIFICATE_OSX_P12 }}
      CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: "16.x"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Add certificates to keychain
        run: chmod +x build/osx-add-cert.sh && build/osx-add-cert.sh # Do not run on local machine
      - name: Rebuild Native Dependencies for x64
        run: ./node_modules/.bin/electron-rebuild --force --arch=x64 --force-abi=101
      - name: Build App
        run: yarn package --arch=x64
      - name: Codesign Mex.app Bundle
        env:
          DEBUG: "*"
        run: node build/darwin-sign.js x64
      - name: Notarize Mex.app Bundle
        run: node build/darwin-notarize.js x64
      - name: Build DMG from Mex.app Bundle
        run: node build/darwin-build-dmg.js x64
      - name: Create Zip from Mex.app Bundle
        run: node build/darwin-build-zip.js x64
      - name: Upload x64 Assets to GitHub Assets Store
        uses: actions/upload-artifact@v2
        with:
          name: mex-x64
          path: ./out/make/*

  publish_on_mac_arm64:
    runs-on: macos-latest
    needs: create_github_release
    env:
      GITHUB_TOKEN: ${{ github.token }}
      YARN_TOKEN: ${{ secrets.YARN_TOKEN }}
      CERTIFICATE_OSX_P12: ${{ secrets.CERTIFICATE_OSX_P12 }}
      CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: "16.x"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Add certificates to keychain
        run: chmod +x build/osx-add-cert.sh && build/osx-add-cert.sh # Do not run on local
      - name: Rebuild Native Dependencies for arm64
        run: ./node_modules/.bin/electron-rebuild --force --arch=arm64 --force-abi=101
      - name: Build App
        run: yarn package --arch=arm64
      - name: Codesign Mex.app Bundle
        env:
          DEBUG: "*"
        run: node build/darwin-sign.js arm64
      - name: Notarize Mex.app Bundle
        run: node build/darwin-notarize.js arm64
      - name: Build DMG from Mex.app Bundle
        run: node build/darwin-build-dmg.js arm64
      - name: Create Zip from Mex.app Bundle
        run: node build/darwin-build-zip.js arm64
      - name: Upload arm64 Assets to GitHub Assets Store
        uses: actions/upload-artifact@v2
        with:
          name: mex-arm64
          path: ./out/make/*

  create_new_ers_release:
    runs-on: ubuntu-latest
    needs: [publish_on_mac_x64, publish_on_mac_arm64]
    env:
      GITHUB_TOKEN: ${{ github.token }}
      YARN_TOKEN: ${{ secrets.YARN_TOKEN }}
      ERS_USERNAME: ${{ secrets.ERS_USERNAME }}
      ERS_PASSWORD: ${{ secrets.ERS_PASSWORD }}
      ERS_BASE_URL: ${{ secrets.ERS_BASE_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: Create out/make directory
        run: mkdir -p out/make
      - name: Download x64 Artifacts
        uses: actions/download-artifact@v2
        with:
          name: mex-x64
          path: out/make
      - name: Download arm64 Artifacts
        uses: actions/download-artifact@v2
        with:
          name: mex-arm64
          path: out/make
      - name: Create Release and Add Assets
        run: python build/upload-ers.py
